[[OSRM]]
arch = "aarch64"
git-tree-sha1 = "dfe3562cfcca9f0c281897da26f25d6d7d6dd521"
os = "macos"

    [[OSRM.download]]
    sha256 = "d5e077bf1884b1e96dec80d97a7d3e7cc5e9c8627b0da8800c6975dbacfbd333"
    url = "https://github.com/jrklasen/OSRM_jll.jl/releases/download/OSRM-v6.0.0+0/OSRM.v6.0.0.aarch64-apple-darwin.tar.gz"
[[OSRM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7eec3634e87bba09859b270e66fd7c753998f18"
libc = "glibc"
os = "linux"

    [[OSRM.download]]
    sha256 = "70f7c466792b3e49e68da6e7365359a98a127d025eb2b77eebb0e54e88aa57e0"
    url = "https://github.com/jrklasen/OSRM_jll.jl/releases/download/OSRM-v6.0.0+0/OSRM.v6.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[OSRM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a45da0e4f94a7fcc567de087963d77e10b585d67"
libc = "musl"
os = "linux"

    [[OSRM.download]]
    sha256 = "81053b1a3839253630b718b54a47e4ca40ca24cbbcdd142f0e2541e7895338c4"
    url = "https://github.com/jrklasen/OSRM_jll.jl/releases/download/OSRM-v6.0.0+0/OSRM.v6.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[OSRM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b935324bf0dfbb7a0335175ccd87a2d15270c86c"
libc = "glibc"
os = "linux"

    [[OSRM.download]]
    sha256 = "48ce0889835577edd670174da8059c6f7c3b9581e11ebe2daf474d77ce405ec7"
    url = "https://github.com/jrklasen/OSRM_jll.jl/releases/download/OSRM-v6.0.0+0/OSRM.v6.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[OSRM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2a4a8e4549e76f14b7f4c1bae9667373e928ca6"
libc = "musl"
os = "linux"

    [[OSRM.download]]
    sha256 = "f1a16e2c6b9b373737a1c8f3b8d9f5a2eaefc9270b3653ed99c6ec1c83e0847e"
    url = "https://github.com/jrklasen/OSRM_jll.jl/releases/download/OSRM-v6.0.0+0/OSRM.v6.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[OSRM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3edbc096942848ee3f815f462c59f5de399b3901"
libc = "glibc"
os = "linux"

    [[OSRM.download]]
    sha256 = "1cf6c2478a22ab2344292471d2bb59d761bb2c2bdc33a57a9b4101c5743ad2f8"
    url = "https://github.com/jrklasen/OSRM_jll.jl/releases/download/OSRM-v6.0.0+0/OSRM.v6.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[OSRM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e0fafa09a0878c81fb484676754e192a93b1ecc9"
libc = "musl"
os = "linux"

    [[OSRM.download]]
    sha256 = "e8c5e8b444b21263d9a9936565d54c813040159f1a943f88fd1736414fd01d41"
    url = "https://github.com/jrklasen/OSRM_jll.jl/releases/download/OSRM-v6.0.0+0/OSRM.v6.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[OSRM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1111511bb6e25effe931b1340933c025311a9325"
libc = "glibc"
os = "linux"

    [[OSRM.download]]
    sha256 = "cd8c98ccdae61073e2ed99fb11d260e7dba617097b42cf18b40e94c8beff6668"
    url = "https://github.com/jrklasen/OSRM_jll.jl/releases/download/OSRM-v6.0.0+0/OSRM.v6.0.0.i686-linux-gnu-cxx11.tar.gz"
[[OSRM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "de3474015df0c30dccca2cf9f1a68b769c5fbe7d"
libc = "musl"
os = "linux"

    [[OSRM.download]]
    sha256 = "4bf0b5949c1419e7d7255301be3e9d4824dd3d39033e21cf606d8bff9396caa4"
    url = "https://github.com/jrklasen/OSRM_jll.jl/releases/download/OSRM-v6.0.0+0/OSRM.v6.0.0.i686-linux-musl-cxx11.tar.gz"
[[OSRM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ffcf1b7eb22adf5e281581a7b921c3a175a1bf8e"
libc = "glibc"
os = "linux"

    [[OSRM.download]]
    sha256 = "2c4a53b56adb62b209ef9694b880019b2d18d62c83f653d9dc682a61ed723fab"
    url = "https://github.com/jrklasen/OSRM_jll.jl/releases/download/OSRM-v6.0.0+0/OSRM.v6.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[OSRM]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a53e54957d4e46c573b69761008756dc7e2148e3"
libc = "glibc"
os = "linux"

    [[OSRM.download]]
    sha256 = "7dd9538b1b1ff73e84ff1fabacaa2e8493f1c8f33b6a51d1b96ea75493c7efeb"
    url = "https://github.com/jrklasen/OSRM_jll.jl/releases/download/OSRM-v6.0.0+0/OSRM.v6.0.0.riscv64-linux-gnu-cxx11.tar.gz"
[[OSRM]]
arch = "x86_64"
git-tree-sha1 = "d047ec0df3641ff6ce05cfb2d8e29c916b1ad332"
os = "macos"

    [[OSRM.download]]
    sha256 = "b8a2bc8eb12038bd0fdda988fd00256ecdddb486df3fd996af353d75dc6a68cb"
    url = "https://github.com/jrklasen/OSRM_jll.jl/releases/download/OSRM-v6.0.0+0/OSRM.v6.0.0.x86_64-apple-darwin.tar.gz"
[[OSRM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "267ceef86ec877f4ad6041cbeba9ea276a994008"
libc = "glibc"
os = "linux"

    [[OSRM.download]]
    sha256 = "0f4c43a63ee6a913cb8010558eb50927fb731eb0974e7e4a331463e60c4f59a7"
    url = "https://github.com/jrklasen/OSRM_jll.jl/releases/download/OSRM-v6.0.0+0/OSRM.v6.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[OSRM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4adefc8d8ee923e3b7e8714532dea2276776db55"
libc = "musl"
os = "linux"

    [[OSRM.download]]
    sha256 = "d9347d40f1bd22b734c87b06e2b205e81eebacecac6cb86cd2067044e421131e"
    url = "https://github.com/jrklasen/OSRM_jll.jl/releases/download/OSRM-v6.0.0+0/OSRM.v6.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[OSRM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6f5f8c995e909f22c50a5fd22a0b8b344d1ebe2"
os = "windows"

    [[OSRM.download]]
    sha256 = "4ab376fd1f2ab8f773b69add9186a84d31ff9a652fc16de52b91b7b67633eb65"
    url = "https://github.com/jrklasen/OSRM_jll.jl/releases/download/OSRM-v6.0.0+0/OSRM.v6.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[OSRM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e64e3d8e4cbeb3dc1414062ca7753a764302e887"
os = "windows"

    [[OSRM.download]]
    sha256 = "4e82d5e966ecbfb271731683f795556ccbfa9e70f41852ac965a6ed1d58177ba"
    url = "https://github.com/jrklasen/OSRM_jll.jl/releases/download/OSRM-v6.0.0+0/OSRM.v6.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
